version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://novel_user:novel_password@db:5432/novel_db
      - DATABASE_URL_UNPOOLED=postgres://novel_user:novel_password@db:5432/novel_db
    depends_on:
      db:
        condition: service_healthy
    restart: always
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npx prisma generate &&
        npm start
      "

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=novel_user
      - POSTGRES_PASSWORD=novel_password
      - POSTGRES_DB=novel_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U novel_user -d novel_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 